package org.group12.model.todo.factories;

import org.group12.model.IDFactory;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Represents a factory for generating IDs for BigTask objects.
 * This class extends the IDFactory abstract class and provides the specific implementation for BigTask.
 */
public class BigTaskIDFactory extends IDFactory {
    private static final String PREFIX = "BTK";
    private static final AtomicLong counter = new AtomicLong(1);
    private static BigTaskIDFactory instance;
    private BigTaskIDFactory(){

    }
    public static synchronized BigTaskIDFactory getInstance(){
        if(instance == null){
            instance = new BigTaskIDFactory();
        }
        return instance;
    }
    /**
     * Returns the prefix for the IDs generated by this factory.
     *
     * @return the prefix for the IDs
     */
    @Override
    protected String getPrefix() {
        return PREFIX;
    }
    /**
     * Returns the counter for the IDs generated by this factory.
     *
     * @return the counter for the IDs
     */
    @Override
    protected AtomicLong getCounter() {
        return counter;
    }

    @Override
    protected String getObjectType() {
        return "Big Task";
    }
}

