package org.group12.model.journal;

import javafx.fxml.Initializable;
import org.group12.model.IDFactory;

import java.util.concurrent.atomic.AtomicLong;
/**
 * Represents a factory for generating IDs for JournalEntry objects.
 * This class extends the IDFactory abstract class and provides the specific implementation for JournalEntries.
 */
public class JournalEntryIDFactory extends IDFactory  {
    private static final String PREFIX = "JE";
    private static final AtomicLong counter = new AtomicLong(1);
    private static JournalEntryIDFactory instance;
    private JournalEntryIDFactory(){

    }
    public static synchronized JournalEntryIDFactory getInstance(){
        if(instance == null){
            instance = new JournalEntryIDFactory();
        }
        return instance;
    }
    /**
     * Returns the prefix for the IDs generated by this factory.
     *
     * @return the prefix for the IDs
     */
    @Override
    protected String getPrefix() {
        return PREFIX;
    }
    /**
     * Returns the counter for the IDs generated by this factory.
     *
     * @return the counter for the IDs
     */
    @Override
    protected AtomicLong getCounter() {
        return counter;
    }

    @Override
    protected String getObjectType() {
        return "Journal Entry";
    }
}

