package org.group12.model.journal;

import org.group12.model.IDFactory;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Represents a factory for generating IDs for Journal objects.
 * This class extends the IDFactory abstract class and provides the specific implementation for Journals.
 */
public class JournalIDFactory extends IDFactory {
    private static final String PREFIX = "JRNL";
    private static final AtomicLong counter = new AtomicLong(1);
    /**
     * Returns the prefix for the IDs generated by this factory.
     *
     * @return the prefix for the IDs
     */
    @Override
    protected String getPrefix() {
        return PREFIX;
    }
    /**
     * Returns the counter for the IDs generated by this factory.
     *
     * @return the counter for the IDs
     */
    @Override
    protected AtomicLong getCounter() {
        return counter;
    }

    @Override
    protected String getObjectType() { return "Journal"; }
}

