package org.group12.model.Calendar;

import org.group12.model.IDFactory;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Represents a factory for generating IDs for TaskList objects.
 * This class extends the IDFactory abstract class and provides the specific implementation for TaskList.
 */
public class EventIdFactory extends IDFactory {
    private static final String PREFIX = "EV";
    private static final AtomicLong counter = new AtomicLong(1);
    private static EventIdFactory instance;
    private EventIdFactory(){

    }
    public static synchronized EventIdFactory getInstance(){
        if(instance == null){
            instance = new EventIdFactory();
        }
        return instance;
    }
    /**
     * Returns the prefix for the IDs generated by this factory.
     *
     * @return the prefix for the IDs
     */
    @Override
    protected String getPrefix() {
        return PREFIX;
    }
    /**
     * Returns the counter for the IDs generated by this factory.
     *
     * @return the counter for the IDs
     */

    @Override
    protected AtomicLong getCounter() {
        return counter;
    }
    @Override
    protected String getObjectType() { return "Event"; }
}
